### ISSUE TITLE
Adapt to Pagekit 1.0.11 and push to Marketplace?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [KnipAG/pagekit-faq#1]
Hi,

I found this extension for Pagekit which looks interesting. Although needs to be installed manually, and it's a little bit out-to-date regarding the way today Pagekit loads the extensions.

Have you got in plan a migration to latest Pagekit version say 1.0.11?

Thank you in advance,
Julian

**Comment by janthurau** [comment]
Hi Julian,

we're not using Pagekit anymore, so there is no plan to maintain the extension. Probably it's faster to build a new extension from scratch anyway.

Sorry!

Best,

**Comment by julianxhokaxhiu** [comment]
Thank you for the feedback :) Best regards
